"""
STASIS Server — Report Generator
Generate daily patrol PDF reports using fpdf2.
"""
import os
import json
import math
from datetime import datetime
from fpdf import FPDF
from database import Database
from config import REPORT_DIR, ROVER_STATES


class ReportGenerator:
    def __init__(self, db: Database):
        self._db = db
        os.makedirs(REPORT_DIR, exist_ok=True)

    def generate_daily_report(self, date_str=None):
        """Generate PDF report for the given date (default: today)."""
        if not date_str:
            date_str = datetime.now().strftime("%Y-%m-%d")

        telemetry = self._db.get_telemetry_for_date(date_str)
        alerts = self._db.get_alerts_for_date(date_str)

        summary = self._compute_summary(telemetry, alerts)

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # Header
        pdf.set_font("Helvetica", "B", 24)
        pdf.set_text_color(45, 106, 79)  # Forest green
        pdf.cell(0, 15, "STASIS", ln=True, align="C")
        pdf.set_font("Helvetica", "", 12)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 8, "Autonomous Forest Patrol Rover — Daily Report", ln=True, align="C")
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 12, f"Date: {date_str}", ln=True, align="C")
        pdf.ln(5)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)

        # Summary Section
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Patrol Summary", ln=True)
        pdf.set_font("Helvetica", "", 10)

        summary_items = [
            f"Total Distance Patrolled: {summary['distance_km']:.2f} km",
            f"Total Telemetry Points: {summary['telemetry_count']}",
            f"Human Detections: {summary['human_detections']}",
            f"Stuck Events: {summary['stuck_events']}",
            f"Low Battery Alerts: {summary['battery_alerts']}",
            f"Tilt Events: {summary['tilt_events']}",
        ]
        for item in summary_items:
            pdf.cell(0, 7, f"  • {item}", ln=True)
        pdf.ln(3)

        # State Time Distribution
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Time in Each State", ln=True)
        pdf.set_font("Helvetica", "", 10)
        for state_name, minutes in summary['state_times'].items():
            pdf.cell(0, 7, f"  • {state_name}: {minutes:.1f} minutes", ln=True)
        pdf.ln(3)

        # Temperature
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Temperature", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, f"  • Min: {summary['temp_min']:.1f}°C", ln=True)
        pdf.cell(0, 7, f"  • Max: {summary['temp_max']:.1f}°C", ln=True)
        pdf.cell(0, 7, f"  • Avg: {summary['temp_avg']:.1f}°C", ln=True)
        pdf.ln(3)

        # Battery
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Battery", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, f"  • Min Voltage: {summary['bat_min']:.2f}V", ln=True)
        pdf.cell(0, 7, f"  • Max Voltage: {summary['bat_max']:.2f}V", ln=True)
        pdf.ln(3)

        # Alerts Detail
        if alerts:
            pdf.set_font("Helvetica", "B", 14)
            pdf.cell(0, 10, "Alert Details", ln=True)
            pdf.set_font("Helvetica", "", 9)

            for alert in alerts:
                pdf.set_font("Helvetica", "B", 10)
                pdf.cell(0, 7,
                         f"[{alert.get('type', 'UNKNOWN')}] "
                         f"{alert.get('timestamp', 'N/A')} — "
                         f"GPS: ({alert.get('lat', 0):.4f}, {alert.get('lon', 0):.4f})",
                         ln=True)
                if alert.get('notes'):
                    pdf.set_font("Helvetica", "I", 9)
                    pdf.cell(0, 6, f"  Notes: {alert['notes']}", ln=True)
                pdf.ln(2)

        # Footer
        pdf.ln(10)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(0, 5, f"Generated by STASIS Server on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
                 ln=True, align="C")

        # Save PDF
        pdf_path = os.path.join(REPORT_DIR, f"{date_str}.pdf")
        pdf.output(pdf_path)

        # Save to database
        self._db.save_report(date_str, pdf_path, summary)

        print(f"[REPORT] Generated: {pdf_path}")
        return pdf_path

    def _compute_summary(self, telemetry, alerts):
        summary = {
            "telemetry_count": len(telemetry),
            "distance_km": 0.0,
            "human_detections": 0,
            "stuck_events": 0,
            "battery_alerts": 0,
            "tilt_events": 0,
            "temp_min": 999,
            "temp_max": -999,
            "temp_avg": 0,
            "bat_min": 999,
            "bat_max": 0,
            "state_times": {}
        }

        # Alert counts
        for alert in alerts:
            atype = alert.get("type", "")
            if atype == "HUMAN":
                summary["human_detections"] += 1
            elif atype == "STUCK":
                summary["stuck_events"] += 1
            elif atype == "LOW_BATTERY":
                summary["battery_alerts"] += 1
            elif atype == "TILT":
                summary["tilt_events"] += 1

        # Telemetry analysis
        temps = []
        state_counts = {}
        prev_lat, prev_lon = None, None
        total_dist = 0.0

        for t in telemetry:
            # Temperature
            temp = t.get("temperature", 0)
            if temp != 0:
                temps.append(temp)
                summary["temp_min"] = min(summary["temp_min"], temp)
                summary["temp_max"] = max(summary["temp_max"], temp)

            # Battery
            bat = t.get("battery", 0)
            if bat > 0:
                summary["bat_min"] = min(summary["bat_min"], bat)
                summary["bat_max"] = max(summary["bat_max"], bat)

            # State time
            state = t.get("rover_state", 0)
            state_name = ROVER_STATES.get(state, f"STATE_{state}")
            state_counts[state_name] = state_counts.get(state_name, 0) + 1

            # Distance
            lat, lon = t.get("lat", 0), t.get("lon", 0)
            if prev_lat is not None and lat != 0 and lon != 0:
                d = self._haversine(prev_lat, prev_lon, lat, lon)
                total_dist += d
            if lat != 0 and lon != 0:
                prev_lat, prev_lon = lat, lon

        summary["distance_km"] = total_dist / 1000.0
        summary["temp_avg"] = sum(temps) / len(temps) if temps else 0
        if summary["temp_min"] == 999:
            summary["temp_min"] = 0
        if summary["temp_max"] == -999:
            summary["temp_max"] = 0
        if summary["bat_min"] == 999:
            summary["bat_min"] = 0

        # Convert state counts to approximate minutes (2s per telemetry)
        for state, count in state_counts.items():
            summary["state_times"][state] = count * 2.0 / 60.0

        return summary

    @staticmethod
    def _haversine(lat1, lon1, lat2, lon2):
        R = 6371000
        dLat = math.radians(lat2 - lat1)
        dLon = math.radians(lon2 - lon1)
        a = (math.sin(dLat / 2) ** 2 +
             math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) *
             math.sin(dLon / 2) ** 2)
        return R * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
