title: STASIS
description: Raspberry Pi rover platform for forest-style monitoring.
baseurl: /Stasis
markdown: kramdown
highlighter: rouge
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
