title: STASIS
description: Raspberry Pi rover platform for field monitoring and object detection.
baseurl: /Stasis
markdown: kramdown
highlighter: rouge
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
